spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxibooking
    username: postgres
<<<<<<< HEAD
    password: devadath@1234
=======
    password: aswa19
>>>>>>> 8ca2ce1d2468ef542064fd84dda471558a6790a3
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


jwt:
  expiry: 36000000
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

server:
  port:
    8090