spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxibooking
    username: postgres
    password: edstem@23
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


jwt:
  expiry: 36000000
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

